using MoneyCalc.Web.Models.Board;
using Npgsql;
using NpgsqlTypes;

namespace MoneyCalc.Web.Services;

public class PostgresBoardRepository(IConfiguration configuration, IBoardPasswordHasher passwordHasher) : IBoardRepository
{
    private const string MissingConnectionStringMessage = "게시판 데이터베이스 연결 문자열이 설정되지 않았습니다.";

    private string ConnectionString =>
        configuration.GetConnectionString("BoardDatabase")
        ?? throw new InvalidOperationException(MissingConnectionStringMessage);

    public async Task EnsureCreatedAsync(CancellationToken cancellationToken = default)
    {
        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync(cancellationToken);

        await using var command = connection.CreateCommand();
        command.CommandText = """
            CREATE TABLE IF NOT EXISTS board_posts (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title varchar(80) NOT NULL,
                author varchar(20) NOT NULL,
                content varchar(4000) NOT NULL,
                password_hash text NOT NULL,
                client_ip varchar(64),
                user_agent varchar(256),
                view_count integer NOT NULL DEFAULT 0,
                is_deleted boolean NOT NULL DEFAULT false,
                created_at timestamptz NOT NULL DEFAULT now()
            );

            CREATE INDEX IF NOT EXISTS ix_board_posts_created_at
                ON board_posts (created_at DESC)
                WHERE is_deleted = false;
            """;

        await command.ExecuteNonQueryAsync(cancellationToken);
    }

    public async Task<BoardIndexViewModel> GetPostsAsync(int page, int pageSize, CancellationToken cancellationToken = default)
    {
        var safePage = Math.Max(1, page);
        var offset = (safePage - 1) * pageSize;

        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync(cancellationToken);

        var totalCount = 0;
        await using (var countCommand = connection.CreateCommand())
        {
            countCommand.CommandText = "SELECT count(*) FROM board_posts WHERE is_deleted = false;";
            totalCount = Convert.ToInt32(await countCommand.ExecuteScalarAsync(cancellationToken));
        }

        var posts = new List<BoardPost>();
        await using (var listCommand = connection.CreateCommand())
        {
            listCommand.CommandText = """
                SELECT id, title, author, content, created_at, view_count
                FROM board_posts
                WHERE is_deleted = false
                ORDER BY id DESC
                LIMIT @pageSize OFFSET @offset;
                """;
            listCommand.Parameters.AddWithValue("pageSize", pageSize);
            listCommand.Parameters.AddWithValue("offset", offset);

            await using var reader = await listCommand.ExecuteReaderAsync(cancellationToken);
            while (await reader.ReadAsync(cancellationToken))
            {
                posts.Add(ReadPost(reader));
            }
        }

        return new BoardIndexViewModel
        {
            Posts = posts,
            CurrentPage = safePage,
            TotalCount = totalCount,
            TotalPages = Math.Max(1, (int)Math.Ceiling(totalCount / (double)pageSize))
        };
    }

    public async Task<BoardPost?> GetPostAsync(int id, bool incrementViewCount, CancellationToken cancellationToken = default)
    {
        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync(cancellationToken);

        if (incrementViewCount)
        {
            await using var updateCommand = connection.CreateCommand();
            updateCommand.CommandText = """
                UPDATE board_posts
                SET view_count = view_count + 1
                WHERE id = @id AND is_deleted = false;
                """;
            updateCommand.Parameters.AddWithValue("id", id);
            await updateCommand.ExecuteNonQueryAsync(cancellationToken);
        }

        await using var command = connection.CreateCommand();
        command.CommandText = """
            SELECT id, title, author, content, created_at, view_count
            FROM board_posts
            WHERE id = @id AND is_deleted = false;
            """;
        command.Parameters.AddWithValue("id", id);

        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        return await reader.ReadAsync(cancellationToken) ? ReadPost(reader) : null;
    }

    public async Task<int> CreatePostAsync(
        BoardPostCreateViewModel post,
        string? clientIp,
        string? userAgent,
        CancellationToken cancellationToken = default)
    {
        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync(cancellationToken);

        await using var command = connection.CreateCommand();
        command.CommandText = """
            INSERT INTO board_posts (title, author, content, password_hash, client_ip, user_agent)
            VALUES (@title, @author, @content, @passwordHash, @clientIp, @userAgent)
            RETURNING id;
            """;
        command.Parameters.AddWithValue("title", post.Title.Trim());
        command.Parameters.AddWithValue("author", post.Author.Trim());
        command.Parameters.AddWithValue("content", post.Content.Trim());
        command.Parameters.AddWithValue("passwordHash", passwordHasher.Hash(post.Password));
        command.Parameters.Add("clientIp", NpgsqlDbType.Varchar).Value = (object?)Truncate(clientIp, 64) ?? DBNull.Value;
        command.Parameters.Add("userAgent", NpgsqlDbType.Varchar).Value = (object?)Truncate(userAgent, 256) ?? DBNull.Value;

        return Convert.ToInt32(await command.ExecuteScalarAsync(cancellationToken));
    }

    public async Task<bool> DeletePostAsync(int id, string password, CancellationToken cancellationToken = default)
    {
        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync(cancellationToken);

        string? storedHash;
        await using (var selectCommand = connection.CreateCommand())
        {
            selectCommand.CommandText = """
                SELECT password_hash
                FROM board_posts
                WHERE id = @id AND is_deleted = false;
                """;
            selectCommand.Parameters.AddWithValue("id", id);
            storedHash = await selectCommand.ExecuteScalarAsync(cancellationToken) as string;
        }

        if (storedHash is null || !passwordHasher.Verify(password, storedHash))
        {
            return false;
        }

        await using var deleteCommand = connection.CreateCommand();
        deleteCommand.CommandText = """
            UPDATE board_posts
            SET is_deleted = true,
                title = '삭제된 글입니다',
                content = '',
                password_hash = ''
            WHERE id = @id AND is_deleted = false;
            """;
        deleteCommand.Parameters.AddWithValue("id", id);

        return await deleteCommand.ExecuteNonQueryAsync(cancellationToken) > 0;
    }

    private static BoardPost ReadPost(NpgsqlDataReader reader)
    {
        return new BoardPost
        {
            Id = reader.GetInt32(0),
            Title = reader.GetString(1),
            Author = reader.GetString(2),
            Content = reader.GetString(3),
            CreatedAt = reader.GetFieldValue<DateTimeOffset>(4),
            ViewCount = reader.GetInt32(5)
        };
    }

    private static string? Truncate(string? value, int maxLength)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return null;
        }

        var trimmed = value.Trim();
        return trimmed.Length <= maxLength ? trimmed : trimmed[..maxLength];
    }
}
