using MoneyCalc.Web.Models.Board;
using Npgsql;
using NpgsqlTypes;

namespace MoneyCalc.Web.Services;

public class PostgresBoardRepository(IConfiguration configuration, IBoardPasswordHasher passwordHasher) : IBoardRepository
{
    private const string MissingConnectionStringMessage = "게시판 데이터베이스 연결 문자열이 설정되지 않았습니다.";

    private string ConnectionString =>
        configuration.GetConnectionString("BoardDatabase")
        ?? throw new InvalidOperationException(MissingConnectionStringMessage);

    public async Task EnsureCreatedAsync(CancellationToken cancellationToken = default)
    {
        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync(cancellationToken);

        await using var command = connection.CreateCommand();
        command.CommandText = """
            CREATE TABLE IF NOT EXISTS board_posts (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title varchar(80) NOT NULL,
                author varchar(20) NOT NULL,
                content varchar(4000) NOT NULL,
                password_hash text NOT NULL,
                client_ip varchar(64),
                user_agent varchar(256),
                view_count integer NOT NULL DEFAULT 0,
                is_deleted boolean NOT NULL DEFAULT false,
                created_at timestamptz NOT NULL DEFAULT now(),
                updated_at timestamptz
            );

            ALTER TABLE board_posts
                ADD COLUMN IF NOT EXISTS updated_at timestamptz;

            CREATE TABLE IF NOT EXISTS board_comments (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                post_id integer NOT NULL REFERENCES board_posts(id) ON DELETE CASCADE,
                author varchar(20) NOT NULL,
                content varchar(1000) NOT NULL,
                password_hash text NOT NULL,
                client_ip varchar(64),
                user_agent varchar(256),
                is_deleted boolean NOT NULL DEFAULT false,
                created_at timestamptz NOT NULL DEFAULT now(),
                updated_at timestamptz
            );

            CREATE INDEX IF NOT EXISTS ix_board_posts_created_at
                ON board_posts (created_at DESC)
                WHERE is_deleted = false;

            CREATE INDEX IF NOT EXISTS ix_board_comments_post_id_created_at
                ON board_comments (post_id, created_at)
                WHERE is_deleted = false;
            """;

        await command.ExecuteNonQueryAsync(cancellationToken);
    }

    public async Task<BoardIndexViewModel> GetPostsAsync(int page, int pageSize, CancellationToken cancellationToken = default)
    {
        var safePage = Math.Max(1, page);
        var offset = (safePage - 1) * pageSize;

        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync(cancellationToken);

        var totalCount = 0;
        await using (var countCommand = connection.CreateCommand())
        {
            countCommand.CommandText = "SELECT count(*) FROM board_posts WHERE is_deleted = false;";
            totalCount = Convert.ToInt32(await countCommand.ExecuteScalarAsync(cancellationToken));
        }

        var posts = new List<BoardPost>();
        await using (var listCommand = connection.CreateCommand())
        {
            listCommand.CommandText = """
                SELECT id, title, author, content, created_at, updated_at, view_count
                FROM board_posts
                WHERE is_deleted = false
                ORDER BY id DESC
                LIMIT @pageSize OFFSET @offset;
                """;
            listCommand.Parameters.AddWithValue("pageSize", pageSize);
            listCommand.Parameters.AddWithValue("offset", offset);

            await using var reader = await listCommand.ExecuteReaderAsync(cancellationToken);
            while (await reader.ReadAsync(cancellationToken))
            {
                posts.Add(ReadPost(reader));
            }
        }

        return new BoardIndexViewModel
        {
            Posts = posts,
            CurrentPage = safePage,
            TotalCount = totalCount,
            TotalPages = Math.Max(1, (int)Math.Ceiling(totalCount / (double)pageSize))
        };
    }

    public async Task<BoardPost?> GetPostAsync(int id, bool incrementViewCount, CancellationToken cancellationToken = default)
    {
        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync(cancellationToken);

        if (incrementViewCount)
        {
            await using var updateCommand = connection.CreateCommand();
            updateCommand.CommandText = """
                UPDATE board_posts
                SET view_count = view_count + 1
                WHERE id = @id AND is_deleted = false;
                """;
            updateCommand.Parameters.AddWithValue("id", id);
            await updateCommand.ExecuteNonQueryAsync(cancellationToken);
        }

        await using var command = connection.CreateCommand();
        command.CommandText = """
            SELECT id, title, author, content, created_at, updated_at, view_count
            FROM board_posts
            WHERE id = @id AND is_deleted = false;
            """;
        command.Parameters.AddWithValue("id", id);

        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        return await reader.ReadAsync(cancellationToken) ? ReadPost(reader) : null;
    }

    public async Task<int> CreatePostAsync(
        BoardPostCreateViewModel post,
        string? clientIp,
        string? userAgent,
        CancellationToken cancellationToken = default)
    {
        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync(cancellationToken);

        await using var command = connection.CreateCommand();
        command.CommandText = """
            INSERT INTO board_posts (title, author, content, password_hash, client_ip, user_agent)
            VALUES (@title, @author, @content, @passwordHash, @clientIp, @userAgent)
            RETURNING id;
            """;
        command.Parameters.AddWithValue("title", post.Title.Trim());
        command.Parameters.AddWithValue("author", post.Author.Trim());
        command.Parameters.AddWithValue("content", post.Content.Trim());
        command.Parameters.AddWithValue("passwordHash", passwordHasher.Hash(post.Password));
        command.Parameters.Add("clientIp", NpgsqlDbType.Varchar).Value = (object?)Truncate(clientIp, 64) ?? DBNull.Value;
        command.Parameters.Add("userAgent", NpgsqlDbType.Varchar).Value = (object?)Truncate(userAgent, 256) ?? DBNull.Value;

        return Convert.ToInt32(await command.ExecuteScalarAsync(cancellationToken));
    }

    public async Task<bool> UpdatePostAsync(BoardPostEditViewModel post, CancellationToken cancellationToken = default)
    {
        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync(cancellationToken);

        string? storedHash;
        await using (var selectCommand = connection.CreateCommand())
        {
            selectCommand.CommandText = """
                SELECT password_hash
                FROM board_posts
                WHERE id = @id AND is_deleted = false;
                """;
            selectCommand.Parameters.AddWithValue("id", post.Id);
            storedHash = await selectCommand.ExecuteScalarAsync(cancellationToken) as string;
        }

        if (storedHash is null || !passwordHasher.Verify(post.Password, storedHash))
        {
            return false;
        }

        await using var updateCommand = connection.CreateCommand();
        updateCommand.CommandText = """
            UPDATE board_posts
            SET title = @title,
                content = @content,
                updated_at = now()
            WHERE id = @id AND is_deleted = false;
            """;
        updateCommand.Parameters.AddWithValue("id", post.Id);
        updateCommand.Parameters.AddWithValue("title", post.Title.Trim());
        updateCommand.Parameters.AddWithValue("content", post.Content.Trim());

        return await updateCommand.ExecuteNonQueryAsync(cancellationToken) > 0;
    }

    public async Task<bool> DeletePostAsync(int id, string password, CancellationToken cancellationToken = default)
    {
        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync(cancellationToken);

        string? storedHash;
        await using (var selectCommand = connection.CreateCommand())
        {
            selectCommand.CommandText = """
                SELECT password_hash
                FROM board_posts
                WHERE id = @id AND is_deleted = false;
                """;
            selectCommand.Parameters.AddWithValue("id", id);
            storedHash = await selectCommand.ExecuteScalarAsync(cancellationToken) as string;
        }

        if (storedHash is null || !passwordHasher.Verify(password, storedHash))
        {
            return false;
        }

        await using var deleteCommand = connection.CreateCommand();
        deleteCommand.CommandText = """
            UPDATE board_posts
            SET is_deleted = true,
                title = '삭제된 글입니다',
                content = '',
                password_hash = ''
            WHERE id = @id AND is_deleted = false;
            """;
        deleteCommand.Parameters.AddWithValue("id", id);

        return await deleteCommand.ExecuteNonQueryAsync(cancellationToken) > 0;
    }

    public async Task<IReadOnlyList<BoardComment>> GetCommentsAsync(int postId, CancellationToken cancellationToken = default)
    {
        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync(cancellationToken);

        await using var command = connection.CreateCommand();
        command.CommandText = """
            SELECT id, post_id, author, content, created_at, updated_at
            FROM board_comments
            WHERE post_id = @postId AND is_deleted = false
            ORDER BY id ASC;
            """;
        command.Parameters.AddWithValue("postId", postId);

        var comments = new List<BoardComment>();
        await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        while (await reader.ReadAsync(cancellationToken))
        {
            comments.Add(ReadComment(reader));
        }

        return comments;
    }

    public async Task<int> CreateCommentAsync(
        BoardCommentCreateViewModel comment,
        string? clientIp,
        string? userAgent,
        CancellationToken cancellationToken = default)
    {
        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync(cancellationToken);

        await using var command = connection.CreateCommand();
        command.CommandText = """
            INSERT INTO board_comments (post_id, author, content, password_hash, client_ip, user_agent)
            SELECT @postId, @author, @content, @passwordHash, @clientIp, @userAgent
            WHERE EXISTS (
                SELECT 1 FROM board_posts WHERE id = @postId AND is_deleted = false
            )
            RETURNING id;
            """;
        command.Parameters.AddWithValue("postId", comment.PostId);
        command.Parameters.AddWithValue("author", comment.Author.Trim());
        command.Parameters.AddWithValue("content", comment.Content.Trim());
        command.Parameters.AddWithValue("passwordHash", passwordHasher.Hash(comment.Password));
        command.Parameters.Add("clientIp", NpgsqlDbType.Varchar).Value = (object?)Truncate(clientIp, 64) ?? DBNull.Value;
        command.Parameters.Add("userAgent", NpgsqlDbType.Varchar).Value = (object?)Truncate(userAgent, 256) ?? DBNull.Value;

        var result = await command.ExecuteScalarAsync(cancellationToken);
        return result is null ? 0 : Convert.ToInt32(result);
    }

    public async Task<bool> UpdateCommentAsync(BoardCommentEditViewModel comment, CancellationToken cancellationToken = default)
    {
        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync(cancellationToken);

        var verified = await VerifyCommentPasswordAsync(connection, comment.Id, comment.PostId, comment.Password, cancellationToken);
        if (!verified)
        {
            return false;
        }

        await using var command = connection.CreateCommand();
        command.CommandText = """
            UPDATE board_comments
            SET content = @content,
                updated_at = now()
            WHERE id = @id AND post_id = @postId AND is_deleted = false;
            """;
        command.Parameters.AddWithValue("id", comment.Id);
        command.Parameters.AddWithValue("postId", comment.PostId);
        command.Parameters.AddWithValue("content", comment.Content.Trim());

        return await command.ExecuteNonQueryAsync(cancellationToken) > 0;
    }

    public async Task<bool> DeleteCommentAsync(BoardCommentDeleteViewModel comment, CancellationToken cancellationToken = default)
    {
        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync(cancellationToken);

        var verified = await VerifyCommentPasswordAsync(connection, comment.Id, comment.PostId, comment.Password, cancellationToken);
        if (!verified)
        {
            return false;
        }

        await using var command = connection.CreateCommand();
        command.CommandText = """
            UPDATE board_comments
            SET is_deleted = true,
                content = '',
                password_hash = ''
            WHERE id = @id AND post_id = @postId AND is_deleted = false;
            """;
        command.Parameters.AddWithValue("id", comment.Id);
        command.Parameters.AddWithValue("postId", comment.PostId);

        return await command.ExecuteNonQueryAsync(cancellationToken) > 0;
    }

    private static BoardPost ReadPost(NpgsqlDataReader reader)
    {
        return new BoardPost
        {
            Id = reader.GetInt32(0),
            Title = reader.GetString(1),
            Author = reader.GetString(2),
            Content = reader.GetString(3),
            CreatedAt = reader.GetFieldValue<DateTimeOffset>(4),
            UpdatedAt = reader.IsDBNull(5) ? null : reader.GetFieldValue<DateTimeOffset>(5),
            ViewCount = reader.GetInt32(6)
        };
    }

    private static BoardComment ReadComment(NpgsqlDataReader reader)
    {
        return new BoardComment
        {
            Id = reader.GetInt32(0),
            PostId = reader.GetInt32(1),
            Author = reader.GetString(2),
            Content = reader.GetString(3),
            CreatedAt = reader.GetFieldValue<DateTimeOffset>(4),
            UpdatedAt = reader.IsDBNull(5) ? null : reader.GetFieldValue<DateTimeOffset>(5)
        };
    }

    private async Task<bool> VerifyCommentPasswordAsync(
        NpgsqlConnection connection,
        int commentId,
        int postId,
        string password,
        CancellationToken cancellationToken)
    {
        await using var command = connection.CreateCommand();
        command.CommandText = """
            SELECT password_hash
            FROM board_comments
            WHERE id = @id AND post_id = @postId AND is_deleted = false;
            """;
        command.Parameters.AddWithValue("id", commentId);
        command.Parameters.AddWithValue("postId", postId);

        var storedHash = await command.ExecuteScalarAsync(cancellationToken) as string;
        return storedHash is not null && passwordHasher.Verify(password, storedHash);
    }

    private static string? Truncate(string? value, int maxLength)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return null;
        }

        var trimmed = value.Trim();
        return trimmed.Length <= maxLength ? trimmed : trimmed[..maxLength];
    }
}
